name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: VaultVulp/gp-docker-action@1.6.0
        with:
          build-context: .
          dockerfile: Dockerfile
          # extract-git-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: tempura
          image-tag: ${{ github.ref_name }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
